## Test version of the dockercompose
## the only difference is the starting command
version: '2'

services:
  ## node API
  api:
    build: ${PWD}/api
    ports:
     - "8080:8080"
    depends_on:
     - database
    environment: 
     PORT: 8080
     MONGO_CONN: "mongodb://database:27017/testDistance"
     GMAPS_API_KEY: ${GMAPS_API_KEY}
    links:
     - database:database
    command: npm test

  ## Postgres DB
  database:
    image: mongo:3.4
    logging:
      driver: none